
import type { IFileHistoryStore } from "../file-history-store/index.js";
import type { IFileIndexStore } from "../file-index-store/index.js";
import type { IMemoryStore, MemoryRepository } from "../memory-store/index.js";
import type { MemoryConfig } from "./system-config.js";
import type { TenantId } from "../../identity/types.js";
import type { CommandExecutionPort, CodeExecutionPort, DocumentToolPort, WorkspaceSearchPort } from "./tool-ports.js";
import type { MemoryToolOperations, RuntimeMemorySessionPort } from "../../tools/MemoryTools/MemoryExecution.js";
import type { SkillToolService } from "../../tools/SkillTools/SkillExecution.js";
import type { TaskToolService } from "../../tools/TaskTools/TaskExecution.js";
import type { AgentConfigService } from "../../services/agent/config/index.js";
import type { AgentDelegationService } from "../../services/agent/delegation/index.js";
import type { AgentExecutionLogger, AgentExecutionService } from "../../services/agent/execution/index.js";
import type { ResumeExecutor } from "../../services/agent/execution/resume-executor.js";
import type { RuntimeCoreService } from "../../services/agent/execution/runtime-core-service.js";
import type { AgentMetricsCollector } from "../../services/agent/metrics/metrics-collector.js";
import type { MemoryRuntimeBindings } from "../../services/agent/memory/runtime-bindings.js";
import type { AsyncKernelEventPersister, AsyncPersisterRunContext } from "../../services/agent/sdk/async-event-persister.js";
import type { ArtifactService } from "../../services/artifacts/artifact-service.js";
import type { TransientArtifactService } from "../../services/artifacts/transient-artifact-service.js";
import type { SystemConfigService } from "../../services/config/system-config-service.js";
import type { McpService } from "../../services/integrations/mcp-service.js";
import type { ModelAdapterService } from "../../services/integrations/model-adapter-service.js";
import type { EmbeddingModelService } from "../../services/knowledge/embedding-model-service.js";
import type { KnowledgeBaseService } from "../../services/knowledge/knowledge-base-service.js";
import type { AgentSessionApplication } from "../../services/sessions/index.js";
import type { ConversationStore } from "../conversation-store/index.js";
import type { SkillLibraryService } from "../../services/skills/skill-library-service.js";
import type { BackgroundTaskService } from "../../services/runtime/background-task-service.js";
import type { DelegationPendingService } from "../../services/runtime/delegation-pending-service.js";
import type { DurableClientEventPublisher } from "../../services/runtime/event-outbox/client-event-publisher.js";
import type { OutboxDispatcher } from "../../services/runtime/event-outbox/dispatcher.js";
import type { HostToolRegistry } from "../../services/runtime/host-tool-registry.js";
import type { PendingInteractionPort } from "./pending-interactions.js";
import type { PermissionPolicyService } from "../../services/runtime/permission-policy-service.js";
import type { RealtimeEventBus } from "./realtime-event-bus.js";
import type { SessionNotificationQueue } from "../../services/runtime/session-notification-queue.js";
import type { AsyncDurableClientEventPublisher } from "../../services/runtime/event-outbox/async-client-event-publisher.js";
import type { AsyncConversationHistoryPort, AsyncProviderContinuationLookupPort, SuspendedSessionControlPort } from "./runtime-async-ports.js";
import type { KnowledgeQueryPort } from "../knowledge/query-port.js";
import type { ExecutionStorage } from "../execution/execution-storage.js";
import type { PathAccessPolicy } from "./path-access-policy.js";
import type { AsyncAnalyticsRepository } from "../storage/async-persistence-ports.js";

export interface RuntimeContainer<TMemoryRepository extends MemoryRepository = IMemoryStore> {
  readonly conversationStore: ConversationStore;
  readonly sessionApplication: AgentSessionApplication;
  readonly realtimeEvents: RealtimeEventBus;
  readonly agentExecution: AgentExecutionService;
  readonly resumeExecutor: ResumeExecutor;
  readonly metricsCollector: AgentMetricsCollector;
  readonly permissionPolicy: PermissionPolicyService;
  readonly agentConfig: AgentConfigService;
  readonly modelAdapter: ModelAdapterService;
  readonly systemConfig: SystemConfigService;
  readonly mcp: McpService;
  readonly fileHistory: IFileHistoryStore;
  readonly fileIndex: IFileIndexStore;
  readonly knowledgeBase: KnowledgeBaseService;
  readonly knowledge: KnowledgeQueryPort;
  readonly artifacts: ArtifactService;
  readonly transientArtifacts: TransientArtifactService;
  readonly embeddingModels: EmbeddingModelService;
  readonly memoryStore: TMemoryRepository;
  readonly memoryTools: MemoryToolOperations;
  readonly memoryContextSourceFactory: MemoryRuntimeBindings["createContextSource"];
  readonly documentTools: DocumentToolPort | null;
  readonly codeExecutionTools: CodeExecutionPort | null;
  readonly skillTools: SkillToolService;
  readonly skillLibrary: SkillLibraryService;
  readonly searchTools: WorkspaceSearchPort | null;
  readonly bashTools: CommandExecutionPort | null;
  readonly backgroundTasks: BackgroundTaskService;
  readonly taskTools: TaskToolService;
  readonly pendingInteractions: PendingInteractionPort;
  readonly hostToolRegistry: HostToolRegistry;
  readonly delegationPending: DelegationPendingService;
  readonly toolsDeps: Omit<import("../../tools/registry.js").BackendToolsDeps, "agent" | "teamName">;
  readonly runtimeCore: RuntimeCoreService;
  readonly agentDelegation: AgentDelegationService;
  readonly outboxDispatcher: OutboxDispatcher;
  readonly clientEvents: DurableClientEventPublisher;
  readonly dataRoot: string;
  close(): void;
}

/**
 * Services prepared by a deployment adapter before the shared agent runtime is assembled.
 * Infrastructure services are narrowed to ports as their deployment-specific implementations
 * are extracted. The memory dependency is the first such boundary.
 */
export interface CoreRuntimeDependencies<TMemoryRepository extends MemoryRepository = MemoryRepository> {
  tenantId: TenantId;
  dataRoot: string;
  memoryConfig: MemoryConfig;
  logger?: AgentExecutionLogger | undefined;
  hooks?: ((registry: HookRegistry) => void) | undefined;
  asyncEventPersisterFactory?: (context: AsyncPersisterRunContext) => AsyncKernelEventPersister;
  asyncConversationHistory?: AsyncConversationHistoryPort;
  asyncProviderContinuations?: AsyncProviderContinuationLookupPort;
  asyncClientEvents?: AsyncDurableClientEventPublisher;
  asyncSuspendedSessionControl?: SuspendedSessionControlPort;
  asyncAnalytics?: AsyncAnalyticsRepository;
  conversationStore: ConversationStore;
  sessionApplication: AgentSessionApplication;
  realtimeEvents: RealtimeEventBus;
  permissionPolicy: PermissionPolicyService;
  agentConfig: AgentConfigService;
  modelAdapter: ModelAdapterService;
  systemConfig: SystemConfigService;
  mcp: McpService;
  fileHistory: IFileHistoryStore;
  fileIndex: IFileIndexStore;
  knowledgeBase: KnowledgeBaseService;
  knowledge: KnowledgeQueryPort;
  artifacts: ArtifactService;
  transientArtifacts: TransientArtifactService;
  embeddingModels: EmbeddingModelService;
  memoryStore: TMemoryRepository;
  memoryBindings: MemoryRuntimeBindings;
  executionStorage: ExecutionStorage;
  pathAccessPolicyFactory: () => PathAccessPolicy;
  documentTools: DocumentToolPort | null;
  codeExecutionTools: CodeExecutionPort | null;
  skillTools: SkillToolService;
  skillLibrary: SkillLibraryService;
  searchTools: WorkspaceSearchPort | null;
  bashTools: CommandExecutionPort | null;
  backgroundTasks: BackgroundTaskService;
  taskTools: TaskToolService;
  notificationQueue: SessionNotificationQueue;
  pendingInteractions: PendingInteractionPort;
  hostToolRegistry: HostToolRegistry;
  delegationPending: DelegationPendingService;
  outboxDispatcher: OutboxDispatcher;
  clientEvents: DurableClientEventPublisher;
  closeInfrastructure(): void;
}
import type { HookRegistry } from "@ragsystem/agent-sdk";
