<template><Teleport to="body"><div v-if="open" class="image-lightbox" tabindex="-1" @click.self="emit('close')" @wheel.prevent="onWheel">
  <div class="image-lightbox__toolbar"><Button variant="secondary" size="sm" @click="zoom(-0.2)">缩小</Button><Button variant="secondary" size="sm" @click="zoom(0.2)">放大</Button><Button variant="secondary" size="sm" @click="rotation += 90">旋转</Button><Button variant="secondary" size="sm" @click="reset">重置</Button><Button variant="secondary" size="sm" @click="emit('close')">关闭</Button></div>
  <Button v-if="images.length > 1" class="image-lightbox__nav image-lightbox__nav--prev" variant="secondary" size="icon" aria-label="上一张" @click="emit('previous')">←</Button>
  <img v-if="current" :src="current.src" :alt="current.alt || ''" class="image-lightbox__image" :style="{ transform: `scale(${scale}) rotate(${rotation}deg)` }" />
  <Button v-if="images.length > 1" class="image-lightbox__nav image-lightbox__nav--next" variant="secondary" size="icon" aria-label="下一张" @click="emit('next')">→</Button>
  <div v-if="current" class="image-lightbox__caption">{{ current.alt }}<span v-if="images.length > 1"> · {{ index + 1 }}/{{ images.length }}</span></div>
</div></Teleport></template>
<script setup>import { onBeforeUnmount, onMounted, ref, watch } from 'vue'; import { Button } from '../ui/button';
const props=defineProps({open:Boolean,images:{type:Array,default:()=>[]},index:{type:Number,default:0},current:{type:Object,default:null}});const emit=defineEmits(['close','previous','next']);const scale=ref(1);const rotation=ref(0);const reset=()=>{scale.value=1;rotation.value=0;};const zoom=delta=>{scale.value=Math.min(5,Math.max(.2,scale.value+delta));};const onWheel=e=>zoom(e.deltaY>0?-.15:.15);const onKey=e=>{if(!props.open)return;if(e.key==='Escape')emit('close');if(e.key==='ArrowLeft')emit('previous');if(e.key==='ArrowRight')emit('next');};watch(()=>props.index,reset);onMounted(()=>window.addEventListener('keydown',onKey));onBeforeUnmount(()=>window.removeEventListener('keydown',onKey));</script>
<style scoped>.image-lightbox{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.88);z-index:1000;overflow:hidden}.image-lightbox__toolbar{position:absolute;top:20px;display:flex;gap:8px}.image-lightbox__image{max-width:86vw;max-height:78vh;object-fit:contain;transition:transform .15s}.image-lightbox__nav{position:absolute;top:50%;transform:translateY(-50%)}.image-lightbox__nav--prev{left:24px}.image-lightbox__nav--next{right:24px}.image-lightbox__caption{position:absolute;bottom:20px;color:white}</style>
