import type { AsyncKnowledgeCollectionSummary, AsyncKnowledgeDocumentIndexSummary, AsyncKnowledgeVectorStore, AsyncVectorRecord, AsyncVectorSearchHit, AsyncVectorSearchInput } from "../../../contracts/knowledge/async-vector-store.js";
import type { PostgresMemoryExecutor } from "./memory-repository.js";
const vectorParam = (vector: number[]) => `[${vector.join(",")}]`;
export class PostgresPgVectorRepository implements AsyncKnowledgeVectorStore {
  constructor(private readonly executor: PostgresMemoryExecutor) {}
  async upsertChunks(records: AsyncVectorRecord[]): Promise<void> { for (const record of records) { if (!record.embedding.length) throw new Error("pgvector embedding must not be empty"); await this.executor.query(`INSERT INTO knowledge_vector_chunks(tenant_id,collection,document_id,model_id,chunk_index,content,metadata,embedding,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::vector,CURRENT_TIMESTAMP) ON CONFLICT (tenant_id,collection,document_id,model_id,chunk_index) DO UPDATE SET content=EXCLUDED.content,metadata=EXCLUDED.metadata,embedding=EXCLUDED.embedding,updated_at=CURRENT_TIMESTAMP`, [record.tenant_id, record.collection, record.document_id, record.model_id, record.chunk_index, record.content, JSON.stringify(record.metadata ?? {}), vectorParam(record.embedding)]); } }
  async search(input: AsyncVectorSearchInput): Promise<AsyncVectorSearchHit[]> { const limit = Math.max(1, Math.min(100, Math.floor(input.top_k))); const result = await this.executor.query(`SELECT id,tenant_id,collection,document_id,model_id,chunk_index,content,metadata,1 - (embedding <=> $5::vector) AS vector_score FROM knowledge_vector_chunks WHERE tenant_id=$1 AND collection=$2 AND model_id=$3 ORDER BY embedding <=> $5::vector LIMIT $4`, [input.tenant_id, input.collection, input.model_id, limit, vectorParam(input.query_vector)]); return result.rows.map((row) => ({ id: String(row.id), tenant_id: String(row.tenant_id), collection: String(row.collection), document_id: String(row.document_id), model_id: Number(row.model_id), chunk_index: Number(row.chunk_index), content: String(row.content), metadata: (row.metadata ?? {}) as Record<string, unknown>, vector_score: Number(row.vector_score) })); }
  async listCollections(tenantId: string): Promise<AsyncKnowledgeCollectionSummary[]> { const result = await this.executor.query(`SELECT collection AS name,COUNT(DISTINCT document_id)::int AS document_count,COUNT(*)::int AS chunk_count,NULL::int AS embedding_dimension FROM knowledge_vector_chunks WHERE tenant_id=$1 GROUP BY collection ORDER BY collection`, [tenantId]); return result.rows.map((row) => ({ name: String(row.name), document_count: Number(row.document_count), chunk_count: Number(row.chunk_count), total_chunks: Number(row.chunk_count), embedding_dimension: row.embedding_dimension == null ? null : Number(row.embedding_dimension) })); }
  async listDocumentIndexes(tenantId: string): Promise<AsyncKnowledgeDocumentIndexSummary[]> { const result = await this.executor.query(`SELECT collection,document_id,model_id,COUNT(*)::int AS chunk_count FROM knowledge_vector_chunks WHERE tenant_id=$1 GROUP BY collection,document_id,model_id ORDER BY collection,document_id,model_id`, [tenantId]); return result.rows.map((row) => ({ collection: String(row.collection), document_id: String(row.document_id), model_id: Number(row.model_id), chunk_count: Number(row.chunk_count) })); }
  async deleteChunks(input: { tenant_id: string; collection?: string; document_id?: string; model_id?: number }): Promise<number> { const clauses = ["tenant_id=$1"]; const params: unknown[] = [input.tenant_id]; if (input.collection) { params.push(input.collection); clauses.push(`collection=$${params.length}`); } if (input.document_id) { params.push(input.document_id); clauses.push(`document_id=$${params.length}`); } if (input.model_id != null) { params.push(input.model_id); clauses.push(`model_id=$${params.length}`); } const result = await this.executor.query(`DELETE FROM knowledge_vector_chunks WHERE ${clauses.join(" AND ")}`, params); return Number(result.rowCount ?? 0); }
}
